# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2023-01-22 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryId', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('inventoryName', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[(b'Consumable', b'consumable'), (b'Non-Consumable', b'non_consumable')], default=b'consumable', max_length=150)),
                ('inventoryType', models.CharField(max_length=100)),
                ('inventoryQuantity', models.IntegerField(blank=True)),
                ('inventoryUnit', models.CharField(max_length=15)),
                ('inventoryTotal', models.IntegerField(blank=True)),
                ('quantityLevel', models.FloatField(null=True)),
                ('inventoryDate', models.DateTimeField()),
                ('inventoryStatus', models.IntegerField(default=1)),
                ('inventoryComment', models.CharField(blank=True, max_length=500)),
                ('inventoryExpiryDate', models.DateTimeField()),
                ('inventoryLastUpdatedDate', models.DateTimeField()),
                ('emailFlag', models.IntegerField(default=1)),
                ('inventoryStatusFlag', models.IntegerField(default=1)),
                ('alternateEmail', models.CharField(blank=True, max_length=100)),
                ('referenceInventoryID', models.IntegerField(blank=True)),
                ('isDisable', models.IntegerField(default=0)),
                ('purchaseUnit', models.CharField(blank=True, max_length=100, null=True)),
                ('materialCode', models.CharField(default=b'', max_length=100)),
                ('unitQuantity', models.FloatField(default=1)),
                ('tax', models.FloatField(default=0)),
                ('hsn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('catalog_code', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
